name: CodeQL
on: [pull_request]
jobs:
  analyze:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14

      - name: Install dependencies
        run: npm install
      - uses: github/codeql-action/init@v3
      - uses: github/codeql-action/analyze@v3
