name: CodeQL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

permissions:
  packages: read
  actions: read
  contents: read
  security-events: write

jobs:
  setup:
    uses: ./.github/workflows/prepare.yml
  analyze:
    needs: setup

    runs-on: ubuntu-latest
    steps:
      - uses: github/codeql-action/init@v3
      - uses: github/codeql-action/analyze@v3
