name: CodeQL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  setup:
    uses: ./.github/workflows/prepare.yml
  analyze:
    needs: setup
    permissions:
      packages: read
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: github/codeql-action/init@v3
      - uses: github/codeql-action/analyze@v3
