name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  prettier:
    needs: setup
    uses: ./.github/workflows/prettier.yml
#   eslint:
#     needs: setup
#     uses: ./.github/workflows/eslint.yml

#   codeql:
#     needs: setup
#     uses: ./.github/workflows/codeql.yml
