name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  prettier:
    needs: setup
    uses: ./.github/workflows/code-quality/prettier.yml

  eslint:
    needs: setup
    uses: ./.github/workflows/code-quality/eslint.yml

  codeql:
    needs: setup
    uses: ./.github/workflows/security/codeql.yml
