name: Prettier Check

on: [pull_request]
permissions:
  packages: read
  actions: read
  contents: read
  security-events: write

jobs:
  setup:
    uses: ./.github/workflows/prepare.yml
  check-format:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Check formatting with Prettier
        run: npx prettier --check .
